### ISSUE TITLE
Which one to pick

### ISSUE THREAD

**Issue by X3eRo0** [oozo/gl-ar300m-wifipineapple#1]
This one https://www.amazon.in/dp/B01K6MHRJI/ref=cm_sw_r_cp_apa_i_PVP9AbEPPFQFA

Or this one GL.iNet GL-AR300M-Lite Mini Router https://www.amazon.in/dp/B073TT7KB2/ref=cm_sw_r_cp_apa_i_G1P9Ab0QSWFJF

The first link or the second link

**Comment by q-a-z** [comment]
With external antennas is better of course.
btw, try aliexpress, it may be little cheaper there

**Comment by X3eRo0** [comment]
Thanks
